name: 'Simple Github release'
description:
  'Creates a release tag in Github based on package.json version number'
author: 'Daniel Nakamashi <dnakamashi@gmail.com>'

branding:
  icon: 'package'
  color: 'blue'

# Define your inputs here.
inputs:
  token:
    description: 'Token that allows the creation of releases'
    required: true

runs:
  using: node20
  main: dist/index.js
